contact_links:
  - name: ğŸ’¬ Help and Support
    url: https://github.com/ever-co/ever-teams/discussions
    about: Ask questions and discuss with the community on GitHub Discussions
  - name: ğŸ“š Documentation
    url: https://docs.ever.team
    about: Check the project documentation to find information
  - name: ğŸ¤ Dedicated Support
    url: https://github.com/ever-co/ever-teams#-contact-us
    about: Contact us for dedicated support for Ever Teams
