name: Build and Publish Docker Images Dev

on:
  push:
    branches: [develop]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  ever-teams-webapp:
    runs-on: buildjet-8vcpu-ubuntu-2204

    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Output NEXT_PUBLIC_GAUZY_API_SERVER_URL
        run: echo "NEXT_PUBLIC_GAUZY_API_SERVER_URL=${{ secrets.NEXT_PUBLIC_GAUZY_API_SERVER_URL }}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: |
            ghcr.io/ever-co/ever-teams-webapp-dev:latest
            everco/ever-teams-webapp-dev:latest
            registry.digitalocean.com/ever/ever-teams-webapp-dev:latest
            ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/ever-teams-webapp-dev:latest
          cache-from: type=registry,ref=everco/ever-teams-webapp-dev:latest
          cache-to: type=inline
          build-args: |
            NODE_ENV=development
            NEXT_PUBLIC_GAUZY_API_SERVER_URL=${{ secrets.NEXT_PUBLIC_GAUZY_API_SERVER_URL }}
            NEXT_PUBLIC_GA_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_GA_MEASUREMENT_ID }}
            NEXT_PUBLIC_CAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_CAPTCHA_SITE_KEY }}
            NEXT_PUBLIC_DISABLE_AUTO_REFRESH=false
            NEXT_PUBLIC_COOKIE_DOMAINS=${{ secrets.NEXT_PUBLIC_COOKIE_DOMAINS }}
            NEXT_PUBLIC_BOARD_APP_DOMAIN=${{ secrets.NEXT_PUBLIC_BOARD_APP_DOMAIN }}
            NEXT_PUBLIC_BOARD_BACKEND_POST_URL=${{ secrets.NEXT_PUBLIC_BOARD_BACKEND_POST_URL }}
            NEXT_PUBLIC_BOARD_FIREBASE_CONFIG=${{ secrets.NEXT_PUBLIC_BOARD_FIREBASE_CONFIG }}
            NEXT_PUBLIC_MEET_DOMAIN=${{ secrets.NEXT_PUBLIC_MEET_DOMAIN }}
            NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
            NEXT_PUBLIC_SENTRY_DEBUG=${{ secrets.NEXT_PUBLIC_SENTRY_DEBUG }}
            NEXT_PUBLIC_JITSU_BROWSER_URL=${{ secrets.NEXT_PUBLIC_JITSU_BROWSER_URL }}
            NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY=${{ secrets.NEXT_PUBLIC_JITSU_BROWSER_WRITE_KEY }}
            NEXT_PUBLIC_GITHUB_APP_NAME=ever-github
            NEXT_PUBLIC_CHATWOOT_API_KEY=${{ secrets.NEXT_PUBLIC_CHATWOOT_API_KEY }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub Registry
        run: |
          docker push everco/ever-teams-webapp-dev:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 3600

      - name: Push to DigitalOcean Registry
        run: |
          docker push registry.digitalocean.com/ever/ever-teams-webapp-dev:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Push to Github Registry
        run: |
          docker push ghcr.io/ever-co/ever-teams-webapp-dev:latest

      - name: Login to CW Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CW_DOCKER_REGISTRY }}
          username: ${{ secrets.CW_DOCKER_USER }}
          password: ${{ secrets.CW_DOCKER_USER_PASSWORD }}

      - name: Push to CW Registry
        run: |
          docker push ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/ever-teams-webapp-dev:latest
